/**
 * Expo config plugin: withAndroidIme (chunk C4).
 *
 * During `expo prebuild -p android` this plugin makes the generated app module a
 * fully-registered voice keyboard:
 *   (a) registers the `OpenFlowIme` InputMethodService `<service>` in
 *       AndroidManifest with `BIND_INPUT_METHOD`, the `android.view.InputMethod`
 *       intent-filter, and the `android.view.im` meta-data pointing at
 *       `@xml/method`;
 *   (b) adds the RECORD_AUDIO + INTERNET permissions and a `<queries>` entry for
 *       `android.speech.RecognitionService` (Android 11+ package visibility so the
 *       on-device `stt.mode="local"` engine is discoverable);
 *   (c) copies the authored Kotlin sources from `android-ime/src/main/**` and the
 *       JVM contract tests from `android-ime/src/test/**` into the app module,
 *       and mirrors the shared HTTP fixtures into the unit-test resources so
 *       `./gradlew testDebugUnitTest` runs the contract tests (see
 *       `android-ime/src/test/.../OpenFlowHttpContractTest.kt`);
 *   (d) writes `res/xml/method.xml` (a keyboard IME subtype labelled "OpenFlow")
 *       and a namespaced `res/values/openflow_ime.xml` string used by it;
 *   (e) injects the gradle deps: `androidx.security:security-crypto`
 *       (EncryptedSharedPreferences) plus `junit` + a real `org.json` on the
 *       unit-test classpath.
 *
 * File copying / writing happens only inside a `withDangerousMod` (per Expo
 * guidance) so introspection stays intact. Gradle deps are injected with the
 * idempotent, tagged `mergeContents` helper rather than a raw regex.
 *
 * @param {import('@expo/config-plugins').ExpoConfig} config
 */
const {
  withAndroidManifest,
  withDangerousMod,
  withAppBuildGradle,
  AndroidConfig,
} = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');
const fs = require('fs');
const path = require('path');

const IME_PACKAGE = 'computer.openflow.mobile.ime';
const IME_SERVICE = `${IME_PACKAGE}.OpenFlowIme`;

// Package-visibility query so the on-device (local) STT engine is reachable on
// Android 11+ (see withImeManifest).
const RECOGNITION_SERVICE_ACTION = 'android.speech.RecognitionService';

const SECURITY_CRYPTO = 'androidx.security:security-crypto:1.1.0-alpha06';
const JUNIT = 'junit:junit:4.13.2';
const ORG_JSON = 'org.json:json:20240303';

// ---- (a) + (b) AndroidManifest: service + permissions ---------------------

function withImeManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const androidManifest = cfg.modResults;

    // addPermission does not dedupe against permissions the base template already
    // declares (e.g. INTERNET), so guard to avoid duplicate <uses-permission> tags.
    const existing = (androidManifest.manifest['uses-permission'] || []).map(
      (p) => p.$ && p.$['android:name'],
    );
    for (const perm of ['android.permission.RECORD_AUDIO', 'android.permission.INTERNET']) {
      if (!existing.includes(perm)) {
        AndroidConfig.Permissions.addPermission(androidManifest, perm);
      }
    }

    // Android 11+ (API 30) package visibility: without a <queries> entry for the
    // speech RecognitionService, SpeechRecognizer.isRecognitionAvailable() returns
    // false and the on-device (stt.mode="local") path can't see the engine.
    // Idempotent: only add if not already present.
    androidManifest.manifest.queries = androidManifest.manifest.queries || [];
    const hasRecognitionQuery = androidManifest.manifest.queries.some((q) =>
      (q.intent || []).some((i) =>
        (i.action || []).some(
          (a) => a.$ && a.$['android:name'] === RECOGNITION_SERVICE_ACTION,
        ),
      ),
    );
    if (!hasRecognitionQuery) {
      androidManifest.manifest.queries.push({
        intent: [{ action: [{ $: { 'android:name': RECOGNITION_SERVICE_ACTION } }] }],
      });
    }

    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
    app.service = app.service || [];
    const already = app.service.some((s) => s.$ && s.$['android:name'] === IME_SERVICE);
    if (!already) {
      app.service.push({
        $: {
          'android:name': IME_SERVICE,
          'android:label': 'OpenFlow',
          'android:permission': 'android.permission.BIND_INPUT_METHOD',
          'android:exported': 'true',
        },
        'intent-filter': [{ action: [{ $: { 'android:name': 'android.view.InputMethod' } }] }],
        'meta-data': [
          { $: { 'android:name': 'android.view.im', 'android:resource': '@xml/method' } },
        ],
      });
    }
    return cfg;
  });
}

// ---- (c) + (d) Copy Kotlin + tests + fixtures, write res ------------------

const METHOD_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidIme.js (chunk C4). Do not edit in android/. -->
<input-method xmlns:android="http://schemas.android.com/apk/res/android">
  <subtype
      android:label="@string/openflow_ime_subtype_voice"
      android:imeSubtypeMode="keyboard"
      android:isAsciiCapable="true"
      android:imeSubtypeExtraValue="voice" />
</input-method>
`;

const VALUES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidIme.js (chunk C4). -->
<resources>
  <string name="openflow_ime_label">OpenFlow</string>
  <string name="openflow_ime_subtype_voice">OpenFlow Voice</string>
</resources>
`;

function copyDir(srcDir, destDir) {
  if (!fs.existsSync(srcDir)) return;
  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else fs.copyFileSync(src, dest);
  }
}

function withImeFiles(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const appDir = path.join(cfg.modRequest.platformProjectRoot, 'app');
      const imeRoot = path.join(projectRoot, 'android-ime');

      // (c) Kotlin main sources + JVM contract tests.
      copyDir(path.join(imeRoot, 'src', 'main', 'java'), path.join(appDir, 'src', 'main', 'java'));
      copyDir(path.join(imeRoot, 'src', 'test', 'java'), path.join(appDir, 'src', 'test', 'java'));

      // (c) Mirror the shared HTTP fixtures into the unit-test resources so the
      // Kotlin contract test asserts against the SAME source of truth as TS.
      const fixturesSrc = path.join(projectRoot, 'shared', 'fixtures');
      const fixturesDest = path.join(appDir, 'src', 'test', 'resources', 'fixtures');
      fs.mkdirSync(fixturesDest, { recursive: true });
      for (const f of fs.readdirSync(fixturesSrc)) {
        if (f.endsWith('.json')) {
          fs.copyFileSync(path.join(fixturesSrc, f), path.join(fixturesDest, f));
        }
      }

      // (d) IME metadata resources.
      const resXml = path.join(appDir, 'src', 'main', 'res', 'xml');
      const resValues = path.join(appDir, 'src', 'main', 'res', 'values');
      fs.mkdirSync(resXml, { recursive: true });
      fs.mkdirSync(resValues, { recursive: true });
      fs.writeFileSync(path.join(resXml, 'method.xml'), METHOD_XML);
      fs.writeFileSync(path.join(resValues, 'openflow_ime.xml'), VALUES_XML);

      return cfg;
    },
  ]);
}

// ---- (e) Gradle dependencies ----------------------------------------------

function withImeGradle(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidIme: expected app/build.gradle to be groovy, got ${cfg.modResults.language}`,
      );
    }
    cfg.modResults.contents = mergeContents({
      tag: 'openflow-ime-deps',
      src: cfg.modResults.contents,
      newSrc: [
        `    implementation("${SECURITY_CRYPTO}")`,
        `    testImplementation("${JUNIT}")`,
        `    testImplementation("${ORG_JSON}")`,
      ].join('\n'),
      anchor: /dependencies\s*\{/,
      offset: 1,
      comment: '//',
    }).contents;
    return cfg;
  });
}

/** @param {import('@expo/config-plugins').ExpoConfig} config */
function withAndroidIme(config) {
  config = withImeManifest(config);
  config = withImeFiles(config);
  config = withImeGradle(config);
  return config;
}

module.exports = withAndroidIme;
module.exports.default = withAndroidIme;
